//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Gender.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GenderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GenderEntities object using the connection string found in the 'GenderEntities' section of the application configuration file.
        /// </summary>
        public GenderEntities() : base("name=GenderEntities", "GenderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GenderEntities object.
        /// </summary>
        public GenderEntities(string connectionString) : base(connectionString, "GenderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GenderEntities object.
        /// </summary>
        public GenderEntities(EntityConnection connection) : base(connection, "GenderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int DeleteAll()
        {
            return base.ExecuteFunction("DeleteAll");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="pixels">Initial value of the Pixels property.</param>
        /// <param name="mean">Initial value of the Mean property.</param>
        /// <param name="belowMean">Initial value of the BelowMean property.</param>
        /// <param name="aboveMean">Initial value of the AboveMean property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="isTrainingPattern">Initial value of the IsTrainingPattern property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.Byte[] pixels, global::System.Double mean, global::System.Double belowMean, global::System.Double aboveMean, global::System.Boolean gender, global::System.Boolean isTrainingPattern)
        {
            Item item = new Item();
            item.ID = id;
            item.Pixels = pixels;
            item.Mean = mean;
            item.BelowMean = belowMean;
            item.AboveMean = aboveMean;
            item.Gender = gender;
            item.IsTrainingPattern = isTrainingPattern;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Pixels
        {
            get
            {
                return StructuralObject.GetValidValue(_Pixels);
            }
            set
            {
                OnPixelsChanging(value);
                ReportPropertyChanging("Pixels");
                _Pixels = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pixels");
                OnPixelsChanged();
            }
        }
        private global::System.Byte[] _Pixels;
        partial void OnPixelsChanging(global::System.Byte[] value);
        partial void OnPixelsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Mean
        {
            get
            {
                return _Mean;
            }
            set
            {
                OnMeanChanging(value);
                ReportPropertyChanging("Mean");
                _Mean = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mean");
                OnMeanChanged();
            }
        }
        private global::System.Double _Mean;
        partial void OnMeanChanging(global::System.Double value);
        partial void OnMeanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double BelowMean
        {
            get
            {
                return _BelowMean;
            }
            set
            {
                OnBelowMeanChanging(value);
                ReportPropertyChanging("BelowMean");
                _BelowMean = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BelowMean");
                OnBelowMeanChanged();
            }
        }
        private global::System.Double _BelowMean;
        partial void OnBelowMeanChanging(global::System.Double value);
        partial void OnBelowMeanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AboveMean
        {
            get
            {
                return _AboveMean;
            }
            set
            {
                OnAboveMeanChanging(value);
                ReportPropertyChanging("AboveMean");
                _AboveMean = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AboveMean");
                OnAboveMeanChanged();
            }
        }
        private global::System.Double _AboveMean;
        partial void OnAboveMeanChanging(global::System.Double value);
        partial void OnAboveMeanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.Boolean _Gender;
        partial void OnGenderChanging(global::System.Boolean value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsTrainingPattern
        {
            get
            {
                return _IsTrainingPattern;
            }
            set
            {
                OnIsTrainingPatternChanging(value);
                ReportPropertyChanging("IsTrainingPattern");
                _IsTrainingPattern = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTrainingPattern");
                OnIsTrainingPatternChanged();
            }
        }
        private global::System.Boolean _IsTrainingPattern;
        partial void OnIsTrainingPatternChanging(global::System.Boolean value);
        partial void OnIsTrainingPatternChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Rnd
        {
            get
            {
                return _Rnd;
            }
            set
            {
                OnRndChanging(value);
                ReportPropertyChanging("Rnd");
                _Rnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rnd");
                OnRndChanged();
            }
        }
        private Nullable<global::System.Double> _Rnd;
        partial void OnRndChanging(Nullable<global::System.Double> value);
        partial void OnRndChanged();

        #endregion
    
    }

    #endregion
    
}
