#pragma once

#include <memory>
#include <vector>
#include <sstream>
#include <string>
#include <tuple>
#include <exception>
#include <assert.h>
#include <malloc.h>
#include <functional>
#include <list>
#include <algorithm>
#include <unordered_set>
#include <unordered_map>
#include <ppltasks.h>
#include <random>
#include <type_traits>
#include <boost/algorithm/string.hpp>
#include <boost/mpl/assert.hpp>
#include <boost/filesystem.hpp>
#include <boost/optional.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/coroutine/all.hpp>
#include <boost/iterator.hpp>
#include <boost/phoenix.hpp>
#include "ocl.h"