// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Neuroflow.Tests
{
    public partial class NuralNetworkTests
    {
[TestMethod]
[PexGeneratedBy(typeof(NuralNetworkTests))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void CreateStandardMLANetwork920()
{
    this.CreateStandardMLANetwork(8, 8, 8, 3);
}
[TestMethod]
[PexGeneratedBy(typeof(NuralNetworkTests))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void CreateStandardMLANetworkThrowsLockRecursionException435()
{
    this.CreateStandardMLANetwork(8, 8, 8, 2);
}
    }
}
