// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Threading;

namespace Neuroflow.Tests
{
    public partial class NuralNetworkTests
    {
[TestMethod]
[PexGeneratedBy(typeof(NuralNetworkTests))]
[PexRaisedException(typeof(LockRecursionException))]
public void CreateWiredNetworkThrowsLockRecursionException59()
{
    this.CreateWiredNetwork(1, 1, 1);
}
    }
}
