#pragma once

#define BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION

#include <memory>
#include <vector>
#include <sstream>
#include <string>
#include <tuple>
#include <exception>
#include <assert.h>
#include <malloc.h>
#include <functional>
#include <list>
#include <algorithm>
#include <unordered_set>
#include <unordered_map>
#include <random>
#include <type_traits>
#include <map>
#include <unordered_map>
#include <typeinfo>
#include <random>
#include <boost/algorithm/string.hpp>
#include <boost/mpl/assert.hpp>
#include <boost/filesystem.hpp>
#include <boost/optional.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/coroutine/all.hpp>
#include <boost/iterator.hpp>
#include <boost/thread.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/chrono.hpp>
#include "ocl.h"
#include <cpplinq.hpp>
