//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace LeCun.Features
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LeCunDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LeCunDataEntities object using the connection string found in the 'LeCunDataEntities' section of the application configuration file.
        /// </summary>
        public LeCunDataEntities() : base("name=LeCunDataEntities", "LeCunDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LeCunDataEntities object.
        /// </summary>
        public LeCunDataEntities(string connectionString) : base(connectionString, "LeCunDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LeCunDataEntities object.
        /// </summary>
        public LeCunDataEntities(EntityConnection connection) : base(connection, "LeCunDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sample> Samples
        {
            get
            {
                if ((_Samples == null))
                {
                    _Samples = base.CreateObjectSet<Sample>("Samples");
                }
                return _Samples;
            }
        }
        private ObjectSet<Sample> _Samples;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Samples EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSamples(Sample sample)
        {
            base.AddObject("Samples", sample);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LeCunDataModel", Name="Sample")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sample : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sample object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="isTraining">Initial value of the IsTraining property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="imageData">Initial value of the ImageData property.</param>
        public static Sample CreateSample(global::System.Int32 id, global::System.Boolean isTraining, global::System.Byte number, global::System.Byte[] imageData)
        {
            Sample sample = new Sample();
            sample.ID = id;
            sample.IsTraining = isTraining;
            sample.Number = number;
            sample.ImageData = imageData;
            return sample;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsTraining
        {
            get
            {
                return _IsTraining;
            }
            set
            {
                OnIsTrainingChanging(value);
                ReportPropertyChanging("IsTraining");
                _IsTraining = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTraining");
                OnIsTrainingChanged();
            }
        }
        private global::System.Boolean _IsTraining;
        partial void OnIsTrainingChanging(global::System.Boolean value);
        partial void OnIsTrainingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Byte _Number;
        partial void OnNumberChanging(global::System.Byte value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] ImageData
        {
            get
            {
                return StructuralObject.GetValidValue(_ImageData);
            }
            set
            {
                OnImageDataChanging(value);
                ReportPropertyChanging("ImageData");
                _ImageData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageData");
                OnImageDataChanged();
            }
        }
        private global::System.Byte[] _ImageData;
        partial void OnImageDataChanging(global::System.Byte[] value);
        partial void OnImageDataChanged();

        #endregion
    
    }

    #endregion
    
}
