//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]


namespace TEST.DataTransform
{
    #region Contexts
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NeoCompEntities : ObjectContext
    {
        #region Constructors
        /// <summary>
        /// Initializes a new NeoCompEntities object using the connection string found in the 'NeoCompEntities' section of the application configuration file.
        /// </summary>
        public NeoCompEntities() : base("name=NeoCompEntities", "NeoCompEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NeoCompEntities object.
        /// </summary>
        public NeoCompEntities(string connectionString) : base(connectionString, "NeoCompEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NeoCompEntities object.
        /// </summary>
        public NeoCompEntities(EntityConnection connection) : base(connection, "NeoCompEntities")
        {
            OnContextCreated();
        }
        #endregion
        
        #region Partial Methods
        partial void OnContextCreated();
        #endregion
        
        #region ObjectSet Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TEST01> TEST01
        {
            get
            {
                if ((_TEST01 == null))
                {
                    _TEST01 = base.CreateObjectSet<TEST01>("TEST01");
                }
                return _TEST01;
            }
        }
        private ObjectSet<TEST01> _TEST01;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Police> Police
        {
            get
            {
                if ((_Police == null))
                {
                    _Police = base.CreateObjectSet<Police>("Police");
                }
                return _Police;
            }
        }
        private ObjectSet<Police> _Police;
    
        #endregion
        #region AddTo Methods
            
        /// <summary>
        /// Deprecated Method for adding a new object to the TEST01 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTEST01(TEST01 tEST01)
        {
            base.AddObject("TEST01", tEST01);
        }
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Police EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPolice(Police police)
        {
            base.AddObject("Police", police);
        }
        #endregion
    }
    
    #endregion
    
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NeoCompModel", Name="Police")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Police : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new Police object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="avG">Initial value of the AvG property.</param>
        /// <param name="chdn">Initial value of the Chdn property.</param>
        /// <param name="exEd">Initial value of the ExEd property.</param>
        /// <param name="cR">Initial value of the CR property.</param>
        /// <param name="sexIsF">Initial value of the SexIsF property.</param>
        /// <param name="secE">Initial value of the SecE property.</param>
        /// <param name="avgE">Initial value of the AvgE property.</param>
        /// <param name="finalE">Initial value of the FinalE property.</param>
        public static Police CreatePolice(global::System.Int32 id, global::System.Int32 age, global::System.Double avG, global::System.Int32 chdn, global::System.Int32 exEd, global::System.Boolean cR, global::System.Boolean sexIsF, global::System.Boolean secE, global::System.Double avgE, global::System.String finalE)
        {
            Police police = new Police();
            police.ID = id;
            
            police.Age = age;
            
            police.AvG = avG;
            
            police.Chdn = chdn;
            
            police.ExEd = exEd;
            
            police.CR = cR;
            
            police.SexIsF = sexIsF;
            
            police.SecE = secE;
            
            police.AvgE = avgE;
            
            police.FinalE = finalE;
            
            return police;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
                
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
                
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvG
        {
            get
            {
                return _AvG;
            }
            set
            {
                OnAvGChanging(value);
                ReportPropertyChanging("AvG");
                _AvG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvG");
                OnAvGChanged();
            }
                
        }
        private global::System.Double _AvG;
        partial void OnAvGChanging(global::System.Double value);
        partial void OnAvGChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Chdn
        {
            get
            {
                return _Chdn;
            }
            set
            {
                OnChdnChanging(value);
                ReportPropertyChanging("Chdn");
                _Chdn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chdn");
                OnChdnChanged();
            }
                
        }
        private global::System.Int32 _Chdn;
        partial void OnChdnChanging(global::System.Int32 value);
        partial void OnChdnChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExEd
        {
            get
            {
                return _ExEd;
            }
            set
            {
                OnExEdChanging(value);
                ReportPropertyChanging("ExEd");
                _ExEd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExEd");
                OnExEdChanged();
            }
                
        }
        private global::System.Int32 _ExEd;
        partial void OnExEdChanging(global::System.Int32 value);
        partial void OnExEdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CR
        {
            get
            {
                return _CR;
            }
            set
            {
                OnCRChanging(value);
                ReportPropertyChanging("CR");
                _CR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CR");
                OnCRChanged();
            }
                
        }
        private global::System.Boolean _CR;
        partial void OnCRChanging(global::System.Boolean value);
        partial void OnCRChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SexIsF
        {
            get
            {
                return _SexIsF;
            }
            set
            {
                OnSexIsFChanging(value);
                ReportPropertyChanging("SexIsF");
                _SexIsF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SexIsF");
                OnSexIsFChanged();
            }
                
        }
        private global::System.Boolean _SexIsF;
        partial void OnSexIsFChanging(global::System.Boolean value);
        partial void OnSexIsFChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SecE
        {
            get
            {
                return _SecE;
            }
            set
            {
                OnSecEChanging(value);
                ReportPropertyChanging("SecE");
                _SecE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SecE");
                OnSecEChanged();
            }
                
        }
        private global::System.Boolean _SecE;
        partial void OnSecEChanging(global::System.Boolean value);
        partial void OnSecEChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvgE
        {
            get
            {
                return _AvgE;
            }
            set
            {
                OnAvgEChanging(value);
                ReportPropertyChanging("AvgE");
                _AvgE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgE");
                OnAvgEChanged();
            }
                
        }
        private global::System.Double _AvgE;
        partial void OnAvgEChanging(global::System.Double value);
        partial void OnAvgEChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FinalE
        {
            get
            {
                return _FinalE;
            }
            set
            {
                OnFinalEChanging(value);
                ReportPropertyChanging("FinalE");
                _FinalE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FinalE");
                OnFinalEChanged();
            }
                
        }
        private global::System.String _FinalE;
        partial void OnFinalEChanging(global::System.String value);
        partial void OnFinalEChanged();
        
        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NeoCompModel", Name="TEST01")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TEST01 : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new TEST01 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="vitality">Initial value of the Vitality property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="strike">Initial value of the Strike property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static TEST01 CreateTEST01(global::System.Int32 id, global::System.Double vitality, global::System.Double time, global::System.Double strike, global::System.Double price)
        {
            TEST01 tEST01 = new TEST01();
            tEST01.ID = id;
            
            tEST01.Vitality = vitality;
            
            tEST01.Time = time;
            
            tEST01.Strike = strike;
            
            tEST01.Price = price;
            
            return tEST01;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
                
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Vitality
        {
            get
            {
                return _Vitality;
            }
            set
            {
                OnVitalityChanging(value);
                ReportPropertyChanging("Vitality");
                _Vitality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vitality");
                OnVitalityChanged();
            }
                
        }
        private global::System.Double _Vitality;
        partial void OnVitalityChanging(global::System.Double value);
        partial void OnVitalityChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
                
        }
        private global::System.Double _Time;
        partial void OnTimeChanging(global::System.Double value);
        partial void OnTimeChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Strike
        {
            get
            {
                return _Strike;
            }
            set
            {
                OnStrikeChanging(value);
                ReportPropertyChanging("Strike");
                _Strike = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Strike");
                OnStrikeChanged();
            }
                
        }
        private global::System.Double _Strike;
        partial void OnStrikeChanging(global::System.Double value);
        partial void OnStrikeChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
                
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();
        
        #endregion
    
    }
    
    #endregion
    
}
